# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
#url: "http://vrcooper.github.io" # the base hostname & protocol for your site
url: "http://virginiarcooper.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Virginia Cooper # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Bilingual Full Stack Web Developer</h1>
     <p>I'm a German to English translator and web developer currently based in the San Francisco Bay Area.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: "vcooper2015@hotmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "vrcooper" 
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/coopervirginiawebdev"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "http://stackexchange.com/users/5287763/virginia"
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-84357160-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
